### ISSUE TITLE
Inbounds with duplicate/empty ports

### ISSUE THREAD

**Issue by arash88** [alireza0/x-ui#120]
Hey alireza jan,
When you create Inbounds using fallbacks + **Linux socket files**, you only specify the "listen" textbox (like /run/nginx-h1.socket) and leave the port blank. as a result it saves the inbound with port 0 and won't allow you to make another inbound with an empty port again.

**Comment by alireza0** [comment]
Hello @arash88 
You are right. In the panel's database design, it is defined and will controll it by this way.
Practicaly when you using linux socket or `@service_name` in `listen` box, you don't need to define a port. And if you define any, it will be ignored by `xray-core`.
But due to database schema and ability to remove `listen` simply, it is better to add decorative unique port number.
