### ISSUE TITLE
Limit user concurrent logins

### ISSUE THREAD

**Issue by alirezarm78** [alireza0/x-ui#14]
Is it possible to enable this feature?

**Comment by alireza0** [comment]
In this fork, I removed the IP-Limit from [HexaSoftwareTech's x-ui](https://github.com/HexaSoftwareTech/x-ui).
The reason was it is using [XTLS's xray-core](https://github.com/XTLS/Xray-core) directly. HexaSoftwareTech's package is using [its own forked xray-core](https://github.com/HexaSoftwareTech/Xray-core) and may updated rarely.
Another disadvantage is that IP-Limit solution is not working properly.

I strongly recommend you to use [HexaSoftwareTech's x-ui](https://github.com/HexaSoftwareTech/x-ui) package if you need this feature.

**Comment by alirezarm78** [comment]
Yes of course that solution not work perfectly.
I recommended if you can create some features like this
It will be great

**Comment by alireza0** [comment]
I will check this ability. But I know that there are more enthusiasm to use last version of pure xray-core.

**Comment by mostafa9112** [comment]
Hello, to solve this issue, is it possible to save the connected IPs of each client and just display them in api?
Without using IP restrictions.
