### ISSUE TITLE
Managed to make one inbound to control all other inbounds for a client , BUT ...

### ISSUE THREAD

**Issue by SomeBytee** [alireza0/x-ui#1436]
Hi again,
sorry to open this comment again
I figured it out and now I can control multiple inbounds for a single user using routing rules configuration. and it's working just fine,
the key is creating a single inbound containing user traffic limit and expiration date, and creating outbound for each client in the outbound section in the panel settings. then in the routing rules, I select the inbounds that the user will connect to and instead of redirecting them, I choose the inbound that contains the user's traffic and expiration date and then I redirect the inbound which has the data of each client.

the problem with this is you have to create an outbound for each client ( you can use the script for it anyway ) and in the routing rules section you need to define the Client name on each inbound so it won't interrupt other client settings.

but, I'm one step away from what I want, I did a lot of testing and I'm pretty sure I'm not getting something here
and it's about having different IP servers ( like Germany, Netherlands, USA, and ... ) that clients can connect to.
in the previous we talked that we now managed to control all inbounds using one inbound, now can I use that ONE inbound to go through separated inbounds ( one with a reverse proxy to a USA location and the other one with a reverse proxy to the Netherlands) the base server is Germany which all clients are in there?
like for example, all my inbounds are for connecting to a German server. I have a different inbound which is supposed to go to the USA server ( reverse proxied ) . and because all of them are connecting to one inbound for controlling traffic and expiry date, how I can define that one inbound go to each of these server locations?

LONG STORY SHORT:
need to know, how to define to transfer data from on inbound , to 2 other inbounds , first one will go to USA and second one go to Netherlands server ( which both of them are reverse proxied to my panel)

i need to add something to the topic as well
in my tests :
1- all the data routed through the Netherlands , or the Main inbound which is for controlling inbound would not work anyway
2- couldn't route traffics to Netherlands server but all configs were going through the Main inbound which is for controlling the traffics and expiration date

the key is i want the inbound still can control the traffic and route the traffic based on what client is connecting with . like how i can separate it when it's going through one inbound for 2 different inbound?

I'll send some screenshots of the settings that I already have: ( for now I just want to separate the German inbounds that go to Netherlands server )

![chrome_PYJOz5MQJm](https://github.com/user-attachments/assets/3a06c39a-042f-4662-b8d3-e51fa9f81e78)
![chrome_etKJ67LgU4](https://github.com/user-attachments/assets/96969d9e-5af0-4e9e-8c4a-dc3377f74aec)
![J3jsHpgYC4](https://github.com/user-attachments/assets/8f6ed995-3bbd-4a66-a670-bba822a6c3b0)
![chrome_lHqxGmzHXL](https://github.com/user-attachments/assets/ff61e360-3d79-46c6-9364-9b1bc3195ef4)
![chrome_arvPz6Pxk2](https://github.com/user-attachments/assets/3df4b6dd-a58b-4d99-8f74-3fa445804d98)
![chrome_2z0URqcmBE](https://github.com/user-attachments/assets/698dfb18-b0e8-45e3-92ac-12d08708ebb2)

**Comment by diat01** [comment]
@SomeBytee

Hello, 

First of all, I am new in this field and I hope you know a lot of things because of the question you asked. Can you share with me what you know about how you use this system?

**Comment by sharif221** [comment]
Hello, @SomeBytee 

I think you are doing something wrong here, we don't need this setup to calculate users time and traffic in one place,
You know why?
Because it's not the job of x-ray it's a vpn CORE by setting up complex inbound outbound rules we are not only potentially rune the connection because of all of the back and forth in x-ray core but also making the management harder.
About your question: how to make it multi server:
If there is anyway that you can do it it's wrong: you need to pass all traffic to the next server from the original server, it's not practical for just calculating traffic and time in one place.

What's the solution:
Just use x-ui API with your self written manager
I KNOW you need to sit and write some code but it worth it 

You just connect to 100 server with your code, create 100 client in x-ui for customer and just fetch the traffic for each one in you app, if the sum of traffic exceed the limit just send an API to disable all clients related to one customer.
No x-ray inbound outbound routing rules involved just API

**Comment by alireza0** [comment]
You are looking for `per client classifier` which is not a topic for this panel and core!
And the combination of other tools should be negotiated somewhere else.
