### ISSUE TITLE
Linux Mint support?

### ISSUE THREAD

**Issue by SquadCraftFTW** [alireza0/x-ui#1484]
Hi, I am trying to install on my local machine but get "Your operating system is not supported by this script." error. I have tried installing normally and docker installation but this error always comes if i even type "x-ui"  into terminal.

Is it even possible to install?

**Comment by sharif221** [comment]
The problem is in install.sh file, it doesn't have any section for Linux mint

You can change it and manually bypass the Linux [if else] part, I think it's fine because mint is pretty much Ubuntu.

The second way is using the docker.
Note that docker version do not come with any x-ui menu, you need to go inside the container to use x-ui command
but it's not needed for most parts you can use environment variables while creating docker as explained in document
