### ISSUE TITLE
Problem in add client 

### ISSUE THREAD

**Issue by apkclub051** [alireza0/x-ui#27]
Hi 
Every time to add a new user, there is a connection problem in the client. I understood that by turning off one of these options, a connection is created. Is it possible to remove these two options?  It is really annoying
![IMG_20230226_001326_448](https://user-images.githubusercontent.com/125287371/221378956-f2a363fe-238e-40dc-91c0-9d8479d512ed.jpg)

**Comment by alireza0** [comment]
Hello and thank you for your comment.

If you take a look to the default config from base X-UI of Mr. Asadi and vaxilu, it is always as a hardcoded default configuration.
You can see it [here](https://github.com/HexaSoftwareTech/x-ui/blob/main/web/service/config.json#L58-L71) and [here](https://github.com/vaxilu/x-ui/blob/main/web/service/config.json#L47-L60).

Here is the related codes in default configuration:
```
  "routing": {
    "rules": [
...
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
```

This buttons were requested from a user to make the pannel be able to simply Enable/Disable these parts of default configuraiton.

If you are using DNAT or NGINX's proxy_pass or other address translation, you should remove blocking private IPs. Right now, it is simply available by a pair of buttons! Otherwise you should do it manually in x-ray's default config.

Actually your problem is not here. It might be the problem in `0.3.0` version which was not trigger xray-core auto-restart. And by pushing this buttons, it will be restarted automatically. It was fixed in `0.3.1`.

Please use updated version always!
For your additional information, versoins `0.3.x` had some bugs which I decided to disable it temporary from last version till fixing it fundamentally.
