### ISSUE TITLE
multi domain

### ISSUE THREAD

**Issue by AmoAlireza** [alireza0/x-ui#323]
سلام
دمت گرم و خسته نباشی که این قابلیت اضافه کردی.
قسمت multi domain  وقتی فعال میکنی و مثلا چنتا دامین وارد میکنی اگر با لینک سابسکرایب کانفیگ هارو بگیری پورت همه کانفیگ های دریافتی 1- میزنه و داخل v2rayn ویندوز کلا نوع کانفیگ hysteria_custom میاره و کلا یدونه بیشتر نیست ولی قسمت more information هر کلاینت که بری و بصورت دستی هر کدوم کپی کنی درست کار میکنه.

ورژن برنامه ها در صورت نیاز:
windows v2rayn version: V6.23
android v2rayng version: V1.8.5

**Comment by NimaZare** [comment]
درود و خسته نباشید خدمت مهندسین عزیز
من هم این مشکلات رو دارم و یکی از مشکلات دیگه ای که دوستمون بهش اشاره نکردن این هست:
وقتی برای کانفیگ alpn ست میکنی، با لینک سابسکرایب وارد موبایل که میشه alpn ست نمیکنه فقط fingerprint رو ست میکنه تو کلاینت موبایل.  برای ویندوز هم اصلا اضافه نمیکنه کانفیگ هارو این خطا هارو میده :

Update subscription starts
Subs->Start getting subscriptions
Subs->The SSL connection could not be established, see inner exception.
Subs->Authentication failed because the remote party sent a TLS alert: 'ProtocolVersion'.
Subs->The SSL connection could not be established, see inner exception.
Subs->The SSL connection could not be established, see inner exception.
Subs->The SSL connection could not be established, see inner exception.
Subs->The SSL connection could not be established, see inner exception.
Subs->Invalid subscription content
-------------------------------------------------------
Update subscription end

موقع ساخت کانفیگ قسمت minTLS و maxTLS رو روی 1.3 گذاشتم.

تشکر

**Comment by arash88** [comment]
تو حالت تک پورت کانفیگ هایی که با فالبک هم ساخته میشه باید پورت خود کانفیگ ورودی رو بگیرن که این اتفاق نمیافته

**Comment by alireza0** [comment]
درود بر شما
@AmoAlireza 
بله درست میفرمایید، متاسفانه پورت رو توی vless کامل نکردم و باگ هستش. برای vmess و trojan مشکلی نداره. حتما سریع تصحیح میکنم.

@NimaZare 
این بخش مربود به SSL روی سرویس subscription هست و به کانفیگ inbound ربطی نداره. لطفا چک کنید که certificate های سرویس سابسکریپشن رو درست تنظیم کرده باشید.

@arash88 
آرش عزیز، این موضوع خیلی وقته توی ذهنم هست ولی متاسفانه هنوز نتونستم اجراش کنم.
باید مدل ایجاد لینک برای کاربرانی که از پشت فالبک هستند تبدیل بشه. سعی میکنم سریعتر انجام بدم.

**Comment by arash88** [comment]
داش @alireza0 الماسی داداش، واقعا ممنون، زحمت توسعه x-ui کامل افتاده رو دوش تو🥰
نمیشه مثل قضیه آیپی های کلاد دلخواه که بعد به ساب اضافه میشه پورت هم اضافه بشه؟ یعنی خود کاربر دستی بزنه بره؟
بعد کاش میشد بعضی اینباند ها رو با یه تیک کلا تو ساب نیاورد

**Comment by alireza0** [comment]
دوستان، محاسبه لینک های پشت فالبک هم اضافه شد.
متد تشخیص: استفاده از `@` در ابتدای فیلد listen و ارتباطش با فیلد dest در فالبک.
لطفا به دوستان روش استفاده رو آموزش بدید

**Comment by AmoAlireza** [comment]
@arash88 
آرش جان شما که کامل کار با fallback فولی میشه یه تاپیک درست کنی با عنوان استفاده از یک پورت در چند inbound تا علیرضا جان هم pin کنه 😅

**Comment by alireza0** [comment]
من منتظرم با همکاری IRCF یه راهنمای خوب درست کنیم

**Comment by arash88** [comment]
> دوستان، محاسبه لینک های پشت فالبک هم اضافه شد. متد تشخیص: استفاده از `@` در ابتدای فیلد listen و ارتباطش با فیلد dest در فالبک. لطفا به دوستان روش استفاده رو آموزش بدید

دستت درد نکنه @alireza0 جان عحب روشی زدی فقط اینکه مثلا من با nginx reverse proxy میکنم که دیگه فک نکنم راه ساده ای باشه که با کد تشخیص بده پورت مورد نظر رو و مجبوریم یه جاهایی دستی وارد کنیم.
آموزش فالبک هم [اینجا](https://github.com/iranxray/hope/issues/35) هست کامل.
