### ISSUE TITLE
add user title in bulk add

### ISSUE THREAD

**Issue by MA7** [alireza0/x-ui#40]
Hi,
if add a input for user name in bulk add it will be very useful
for example 
add 5 user with name: demo 
and inbunds emails be look like this: 
-demo01
-demo02
-demo03
...

and thank you for develop this script and add useful features. 🌹🙏🏽

**Comment by Nipoto** [comment]
hi @alireza0 , I did this.

![Untitled](https://user-images.githubusercontent.com/3000646/222712229-1beb89fe-3499-4251-8cfd-a5981c43c677.png)

[web.zip](https://github.com/alireza0/x-ui/files/10881545/web.zip)

**Comment by alireza0** [comment]
Hello @Nipoto @MA7 ,

Thank you for this nice feature.
I am thinking that how we could avoid repeated email?! It couldn't raise a problem due to protection in backend codes.

But what should we do in these cases? :
- When you did bulk creation before and you need more!
- When you have an email like `nima14` somewhere else and want to add 50 new user starintg with `nima` ?
- When you had a bulk 1-50 somewhere else and you need to have a `nima14` manually in other inbound.

Please be informed that final `remark` of the link is the combination of inbound's remark and email, by `-` divider.
So if you need to have prefix, you could count on inbound's `remark`.

Personally I prefer to use random email to avoid duplicate error. Just use `nima` in inbound's `remark` and have `nima-???????` pattern as final `remark`.

**Comment by MA7** [comment]
@alireza0 we can add from and to input for prevent duplicate names.

**Comment by Nipoto** [comment]
@alireza0 this feature _(Prefix)_ is to speed up the creation of an account for a group, such as a family or partner of a particular customer.
In later cases, another name can be used or slightly changed in the prefix. Like: nima1_$i , nima2_$i and etc.
If it is duplicate, it is not possible to register in the database

**Comment by aliafshany** [comment]
@alireza0  in order to have unique emails i do this all the time.

random+ @ + nima1 
for example goriehgaeg@nima1, grwoiggr@nima2, etc ... .

you have that randomizer by default so maybe you can add an option to enter a suffix or prefix.

**Comment by alireza0** [comment]
Hello @Nipoto @MA7 @aliafshany ,

All your ideas are nice.
I will add selectable methods for this part soon.

**Comment by alireza0** [comment]
Done!
Please check manually or wait for next release.

**Comment by arsoltani72** [comment]
راهی هست دستی غیرفال کنم ؟
