### ISSUE TITLE
Direct Country Configs

### ISSUE THREAD

**Issue by Enkidu-6** [alireza0/x-ui#501]
**Describe the bug**

When choosing direct connection to Iran Domains and direct connection to Iran IP ranges, the settings have no effect and the traffic still goes through the main server. 

**To Reproduce**

You can connect to the server using your client and browse to https://websecret.ir/  or  https://kitset.ir/technology/what-is-my-ip-address and examine the IP address shown.

They both have .ir tld however the first web site is served from a Canadian IP address but the second one is served from Tehran and the IP block belongs to Asiatech.

The  Disable connection to Iran's Domains however does work and no connection is made.

The same problem exists on Sanaei Panel .

The clients used are V2rayNG on Android and NekoRay on Windows.

Thank you.

**Comment by alireza0** [comment]
This option will work only when you have chain of proxies.
For instance, if you have iran and germany servers and you connect these two pannels using v2ray tunnel ( outbounds/loadbalancers/reverse ), you should configure it in iran server.
Then traffic will directly route from iran server to the destination. You will see the iran server's IP addres in these websites.

Otherwise, your configuration is not correct.
