### ISSUE TITLE
traffic calculation 

### ISSUE THREAD

**Issue by master2220** [alireza0/x-ui#545]
Hello dear Alireza
First of all thank you for all your efforts to create this panel.
I'm using the latest version of your panel(1.5.5) and the problem I encounter is that after downloading 1.5GB of data it shows that the user consumed about 2.5GB traffic. I tested several times and realized that it always count higher traffic usage than the real amount user consumed.
p.s. I have the same problem in 3x-ui panel and hiddify

**Comment by wulfric93** [comment]
i've encounter this problem as well 
and idk what is the problem here

**Comment by alireza0** [comment]
Hello @master2220 & @wulfric93 
Traffic calculation is not buggy. Please be informed that:
1. Traffic is not only download, but also upload.
2. Traffic is not about what you are downloading in forground. But also background application will use the traffics.
3. X-UI is using traffic report from xray-core and save it without any changes. In some cases, when server has I/O problems which causes dblock, the the trrafic might not be saved. Therefore this calculation might be less than the real consumption and not more!
4. When you have same problem anywhere else, the problem is your type of calculation and assumption. Fix it by yourself :)

**Comment by master2220** [comment]
I've noticed that whenever I use tls methods such as vless ws tls or trojan ws tls and vless grpc tls (using clean cloudflare ip) it calculate traffic about 5 to 10 times more than real traffic spent but if I use direct methods such as vless tcp or vless tcp reality it calculate traffic usage correctly. Maybe cloudflare proxy cause this problem.

**Comment by alireza0** [comment]
You should measure the total device traffic.
However tls connection is entitled to spend more traffic than what you feel on behind of client app.
Please consider re-transimission packets due to lost in the middle of the way by GFW ( specially for TLS connections )

BTW: As I mentioned, traffic calculation is not on the shoulder of x-ui. It gets the reports from xray.

**Comment by master2220** [comment]
@alireza0 
yes ,after testing different methods I realized that it's not panel problem but this bugs occurs for tls connections.
Is there anyway to fix this? I used nekoray to calculate the real traffic spent and after downloading 200MB , in panel it shows 1GB but in direct methods panel traffic calculation and nekoray traffic calculation are the same.

**Comment by alireza0** [comment]
Actually it is not a bug! Your calculation's base is not correct.
Considering packet re-transmission and tls overhead could solve your problem.
To use less ( and not zero ) overhead, you can use `mux` or `Websocket` with `0-RTT` in `TLS` mode.

If you insist on this problem as a bug, it is better to open an issue in `xtls/xray-core` project.

**Comment by master2220** [comment]
I agreed with you that it is not panels bug.
thank you for your time to answer me

**Comment by alireza0** [comment]
No problem
