### ISSUE TITLE
REST Api delete clients in batchs

### ISSUE THREAD

**Issue by ErfanSahabShabani** [alireza0/x-ui#551]
REST Api

**Is your feature request related to a problem? Please describe.**
I am not sure if it is safe for delete client to accept only one client especially if we are going to use the API to delete batchs of clients in a single minute

**Describe the solution you'd like**
Add an api method to delete a batch of clients in a single request, this way we lower the http overhead and more effective this way.

**Describe alternatives you've considered**
I have been thinking of limiting the requests on the code myself to do something like 5 delete requests per 1 second.

**Additional context**
I used other panels not so REST api and the method to delete clients one by one ended up reseting the whole traffics. If you could suggest a soloution or clear me up if the method getting called a lots of time in a minute wont make the database to reset the traffics.

**Comment by alireza0** [comment]
I don't understand what was the problem. But deleting traffics as well as client is the expected behaviour normally.
If by any request, other's traffics become zero, please open a `bug` issue with proper evidences.

In this panel, each request has its own process. The delete request should be done one by one and if you are using shared hosts, it is better to have at least 100ms delay between each request.

If you are trying to delete all depleted users, you can do it in one api call :
POST "/delDepletedClients/:id"
The requested `id` is `inbound_id` and if you set it to `-1` it will run the action for all inbounds.

**Comment by ErfanSahabShabani** [comment]
I see, I shall test the behaviour and if there was an issue with it. The main issue I felt with other panels was I am deleting one user and other users traffic resets aswell which was a wierd behaviour.
