### ISSUE TITLE
Fedora Support OS

### ISSUE THREAD

**Issue by forkeer** [alireza0/x-ui#60]
Please check and approved for Fedora OS support 

https://github.com/alireza0/x-ui/pull/59

Thanks

**Comment by alireza0** [comment]
Hello @forkeer
Thank you for your comment and contribution.
I decided to revert these changes after merge it, because this package will support centos7 and some older ones.
Some users are already using this OS versions and by this changes they cannot update anymore.
Please check this package with older versions of fedora if it supports.

**Comment by forkeer** [comment]
Hi
Please check again 
Fix Fedora OS #66

Thanks for your support

**Comment by alireza0** [comment]
Hello @forkeer ,
Thank you for your nice work. I've just reviewed your codes to ask for adjust it to this panel's code.

Please change requested parameters.
Thanks again

**Comment by forkeer** [comment]
Hi @alireza0 
Done https://github.com/alireza0/x-ui/pull/66
please merge 

Thanks

**Comment by forkeer** [comment]
@alireza0 
Hi
why after merge again revert ?
can you check why happen ?

**Comment by alireza0** [comment]
Hi @forkeer 
Sorry, I had to change my codes due to critical bugs. I will do it again
