### ISSUE TITLE
Geoip rule

### ISSUE THREAD

**Issue by anthey2** [alireza0/x-ui#658]
Hi and thank u so much for this great work!
Having installed xui 1.6.0 on the clean OS i found out that adding "geoip:tm" in the manual list of blocked ips didn't work at all, like it used to in  1.5.5

**Comment by alireza0** [comment]
Hi @anthey2,
Thank you for your report.
It may cause due to several configuration problems.
We are using [LoyalSoldier geoip](https://github.com/Loyalsoldier/geoip) project which contains complete set of countries for a long time.
You may have problem in configuring inbound's `sniffing` or routing rules order is not in correct order.
Other problem may happened when you are using `Domain Routing strategy` to `AsIs` which is changed as default in this version. You can test it with to `IPifNonMatch` and check the result.
