### ISSUE TITLE
Geo enhancement

### ISSUE THREAD

**Issue by shahin-io** [alireza0/x-ui#742]
hello, @alireza0 jan.

in my humble opinion when we use `ext:geoip_IR.dat:ir` simply contains all IP of Iran geolocation. so it is not necessary to use other rules by default. my point of view is to use as little and simple as it can to minimise server load. and for last can u please describe `regexp:.*\\.xn--mgba3a4f16a$` in geosite section.

thanks for everything man.  

![BBA4CFB1-40A0-412B-9748-1D637769C6FA](https://github.com/alireza0/x-ui/assets/115543613/039ce367-72dc-4382-afc3-98cc4a0aef37)

![3C859589-C9AE-454F-ACFD-46EE5D2CCF8B](https://github.com/alireza0/x-ui/assets/115543613/5e7b107e-98d5-4b6c-9698-c6742e23af77)

**Comment by alireza0** [comment]
Hi @shahin-io jan,

I have no idea if it is a complete set of domains/IPs or not, but it is clear that these clouds have a lot of servers world-wide.
This assumption lead me to add these options as well.

Regarding the regexp, it is related to `.ایران` tlds.

**Comment by Enkidu-6** [comment]
> can u please describe `regexp:.*\\.xn--mgba3a4f16a$` in geosite section.

It's called punycode.  Instead of having DNS servers and web servers understand all languages, those languages are transcoded into punycode.

Host names in languages that contain Unicode characters ( like இலங்கை or ایران or ファッション  ) are transcoded into what's also called LDH (Letters, Digits and Hyphens).

You can use [punycode converter](https://www.punycoder.com/) to translate domains in those languages back and forth.
