### ISSUE TITLE
WebRTC public IP with client- server1-server2 connect

### ISSUE THREAD

**Issue by martkotur** [alireza0/x-ui#817]
When setting up client - server 1 - server 2 connections, the webrtc test shows the public address of server 1. The problem occurs on any type of VPN and any transport. There is no such error when connecting the client to the server, only the private address is detected.
tested 
Tested on three vps and different types of clients

![webrtc](https://github.com/alireza0/x-ui/assets/41474898/d75dfdfc-e1eb-4a00-b27a-58602fc3eae8)

**Comment by Enkidu-6** [comment]
WebRTC leaks have nothing to do with what server you're connected to. The server doesn't leak your information, your browser does. Intercepting WebRTC is far too complicated to be integrated into XRay or X-ui and frankly is beyond the mandate of either one.

You can't proxy protocols that you can't directly see or interact with. WebRTC encrypts all traffic using peer-to-peer negotiated certificates for authentication without PKI. Its whole purpose is to bypass all limitations such as NAT and allow people to communicate directly. The only way to do a MiM is to have control of at least one of the peers which is why you can filter it using browser extensions. The extension has control over one of the peers, you. 

If you want WebRTC filtering, you should ask developers of client apps such as V2RayNG, etc... to build it into their apps ( I wouldn't cross my fingers though ) because those apps are running on your OS and have control of one of the peers. Or better yet, just don't use Chrome browser that doesn't allow installation of any add-ons. I have zero WebRTC leaks on any of my systems weather I connect directly or through a VPN.
