### ISSUE TITLE
x-ui new log problem

### ISSUE THREAD

**Issue by X-Oracle** [alireza0/x-ui#947]
Hi Mr. Alireza.
it seems that new logs are making panel slow and sometime makes the panel restart on its own.
I'm saying this since it started when I updated the panel to the version which introduced the feature. rolling back solves the issue.

I am asking if you could have a look on it.
and I would like to suggest if you could add an option to enable/disable catching xray-logs since of the following reasons:
- xray logs are huge amount of data. and catching all may slows panel and even crash on some systems especially old os or slow vps.
- the only use case I see is for debugging configs. in that case we could use the toggle to enable it temporary.

**Comment by alireza0** [comment]
Hello @X-Oracle ,
Yes it is!
Crashes will be fixed by new way in `log_writer` by [this commit]([[logs] new bug-free log_writer](https://github.com/alireza0/x-ui/commit/ee2bbffc8f8b84f34b7db6713e6d7a76320bf702)).

But you are right and it was in my mind to have a place for these configurations.
I will disable it by default and add a GUI for all other configurations.

**Comment by alireza0** [comment]
The simple webform is added now. We could have it in the next version
